name: gwsim
channels:
  - conda-forge
  - igwn
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.4=h0c1763c_0
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.4=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - python=3.11.14=hfe2f287_1_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - astropy==7.1.1
      - astropy-iers-data==0.2025.10.20.0.39.8
      - asttokens==3.0.0
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - bilby==2.7.0
      - bilby-cython==0.5.3
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.2.1
      - comm==0.2.3
      - contourpy==1.3.3
      - corner==2.2.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - cython==3.1.5
      - dateparser==1.2.2
      - debugpy==1.8.17
      - decorator==5.2.1
      - dill==0.4.0
      - dqsegdb2==1.3.0
      - dynesty==3.0.0
      - emcee==3.1.6
      - executing==2.2.1
      - filelock==3.20.0
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - gengli==0.2.0
      - gwdatafind==2.1.0
      - gwosc==0.8.1
      - gwpy==3.0.13
      - gwsim==0.1.dev130+g8ee2c9e61.d20251030
      - h5py==3.15.1
      - idna==3.11
      - igwn-auth-utils==1.4.0
      - igwn-ligolw==2.0.1
      - igwn-segments==2.1.0
      - ipykernel==7.0.1
      - ipython==9.6.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - kiwisolver==1.4.9
      - lalsuite==7.26.1
      - ligotimegps==2.1.0
      - lscsoft-glue==4.1.1
      - mako==1.3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mpld3==0.5.11
      - mpmath==1.3.0
      - msgpack==1.1.2
      - nest-asyncio==1.6.0
      - networkx==3.5
      - numpy==2.3.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pegasus-wms-api==5.1.1
      - pegasus-wms-common==5.1.1
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - prompt-toolkit==3.0.52
      - protobuf==6.33.0
      - psutil==7.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycbc==2.9.0
      - pycparser==2.23
      - pyerfa==2.0.1.5
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pykerr==0.1.0
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - ray==2.50.1
      - referencing==0.37.0
      - regex==2025.10.23
      - requests==2.32.5
      - rich==14.2.0
      - rpds-py==0.27.1
      - safe-netrc==1.0.1
      - scienceplots==2.1.1
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - scitokens==1.8.1
      - shellingham==1.5.4
      - six==1.17.0
      - soupsieve==2.8
      - stack-data==0.6.3
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.9.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.5.0
      - typer==0.20.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - tzlocal==5.3.1
      - urllib3==2.5.0
      - wcwidth==0.2.14
prefix: /home/luca.negri/.conda/envs/gwsim
